.travis.yml
Dockerfile
Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
am-lib/build.gradle
am-lib/gradle.properties
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/DummyService.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/db/migrations/V1__Create_initial_table.sql
am-lib/src/test/java/uk/gov/hmcts/reform/amlib/DummyServiceTest.java
build.gradle
docker-compose.yml
infrastructure/main.tf
infrastructure/output.tf
infrastructure/variables.tf
src/main/java/uk/gov/hmcts/reform/amapi/controllers/RootController.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/amapi/functional/ApplicationTests.java

changed lib artifact id from amlib to am-lib
added migrations files + flyway
consume and configure am-lib in am-lib-testing-api

[AKS] Feature/am 50/configuring testing service

---

am-lib/build.gradle
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/AccessManagementService.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/repositories/AccessManagementRepository.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/AccessManagementServiceIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/amapi/controllers/RootController.java

Added *filterResource* method to AM Service with tests & testing api

[AKS] AM-3basic filter resource with explicit access

---

Jenkinsfile_nightly

Not sure if this is the one you want, but not the rpe one please!

Change nightly slack channel

---

src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/scenarios/BasicScenarios.scala
src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/simulations/PipelineSimulation.scala

Added Get Accessors List Api for performance testing

test: add 'get accessors list' test to suite of performance tests

---

src/gatling/bodies/revokeResourceAccess.json
src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/http/AccessManagement.scala
src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/scenarios/BasicScenarios.scala
src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/simulations/PipelineSimulation.scala

test: added revoke resource access end point test
for more information below screenshot,

test: add revoke resource access endpoint test to performance tests

---

src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/http/AccessManagement.scala
src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/scenarios/BasicScenarios.scala
src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/simulations/PipelineSimulation.scala

hello word scenario has been deleted.

refactor: delete hello word scenario

---

am-lib/build.gradle
build.gradle

build: stop using deprecated Gradle APIs

---

am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/base/IntegrationBaseTest.java
am-lib/src/test/resources/testcontainers.properties

None
Reuses DB container for all tests to speed up test execution

build: reuse DB container for all tests to speed up test execution

---

am-lib/build.gradle
am-lib/config/pmd/ruleset.xml
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/ResourceAttribute.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/ResourceDefinition.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/Role.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/Service.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/repositories/AccessManagementRepository.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/utils/Pair.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GrantAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/RevokeAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/base/IntegrationBaseTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/helpers/DatabaseHelperRepository.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/ResourceDefinitionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/RoleIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/ServiceIntegrationTest.java

refactor: extract helper methods from base integration test to separate repository class

---

src/gatling/bodies/createResourceAccess.json
tools/postman-collections/am-lib-testing.postman_collection.json

refactor:updated security classification in create resource access json file

refactor: update security classification name in performance tests and Postman collections

---

am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetAccessorsListIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetRolePermissionsIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GrantAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/RevokeAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/base/IntegrationBaseTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/base/PreconfiguredIntegrationBaseTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/ResourceDefinitionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/RoleIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/ServiceIntegrationTest.java

None
This PR enforces tables truncate after each integration test to make tests more independent.

refactor: truncate tables after each integration test

---

src/gatling/bodies/createResourceAccess.json
src/gatling/bodies/filterResource.json
src/gatling/bodies/revokeResourceAccess.json
src/main/java/uk/gov/hmcts/reform/amapi/Application.java
src/main/java/uk/gov/hmcts/reform/amapi/config/DefaultRoleSetupImportServiceConfiguration.java
tools/postman-collections/am-lib-testing.postman_collection.json

None
This is to stop relaying on DB migration and use more real life examples

refactor(testing service): populate service and resource definition using importer service

---

am-lib/build.gradle
build.gradle
config/owasp/suppressions.xml

build: upgrade checkstyle to version 8.18 to avoid vulnerability found by OWASP

---

am-lib/build.gradle
am-lib/config/pmd/ruleset.xml
build.gradle
config/pmd/ruleset.xml

build: upgrade PMD to version 6.12 and remove deprecated rule

---

am-lib/src/main/java/uk/gov/hmcts/reform/amlib/AccessManagementService.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportService.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/exceptions/AccessManagementException.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/exceptions/PersistenceException.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/exceptions/UnsupportedPermissionsException.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/aspects/AspectsSuite.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/aspects/ErrorHandlingAspect.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/aspects/ValidationAspect.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/ResourceDefinitionIntegrationTest.java

https://tools.hmcts.net/jira/browse/AM-215
This PR introduces the following improvements:
- JDBI exceptions are wrapped with AM exceptions to keep right abstraction level
- all AM exceptions inherit from base exception to make handling easier
- test: adding missing tests …

refactor: improve error handling

---

am-lib/src/main/java/uk/gov/hmcts/reform/amlib/AccessManagementService.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportService.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/aspects/AuditingAspect.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GrantAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/RevokeAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
am-lib/src/test/java/uk/gov/hmcts/reform/amlib/internal/aspects/AuditingAspectTest.java
am-lib/src/test/java/uk/gov/hmcts/reform/amlib/internal/aspects/StaticLogAppender.java
am-lib/src/test/resources/logback-includes.xml
am-lib/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
src/main/java/uk/gov/hmcts/reform/amapi/controllers/AmLibProxyController.java
tools/postman-collections/am-lib-testing.postman_collection.json

https://tools.hmcts.net/jira/browse/AM-213

feat: add auditing of caller to grant / revoke methods (AM-213)

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized

build: stop the build from deployment to production without failing build

---

am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetResourceDefinitionsWithCreatePermissionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetRolePermissionsIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GrantAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/RevokeAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/base/PreconfiguredIntegrationBaseTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/RoleIntegrationTest.java
am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/DefaultRoleSetupDataFactory.java
am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/TestConstants.java
am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/TestDataFactory.java

refactor: remove unneccessary constants from tests

---

config/owasp/suppressions.xml

build: suppress vulnerability to fix dependency scan issue

---

Jenkinsfile_CNP
am-lib/README.md

build: add publishing Javadoc to pipeline

---

am-lib/README.md
am-lib/docs/importer.md

docs: add importer 'how to' page

---

am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetResourceDefinitionsWithCreatePermissionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetRolePermissionsIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GrantAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/RevokeAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/base/PreconfiguredIntegrationBaseTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/ResourceDefinitionIntegrationTest.java
am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/TestConstants.java

https://tools.hmcts.net/jira/browse/AM-245

refactor: randomise resource type

---

am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetResourceDefinitionsWithCreatePermissionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetRolePermissionsIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GrantAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/RevokeAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/base/PreconfiguredIntegrationBaseTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/ResourceDefinitionIntegrationTest.java
am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/TestConstants.java

https://tools.hmcts.net/jira/browse/AM-245

refactor: random resource name

---

am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetRolePermissionsIntegrationTest.java

https://tools.hmcts.net/jira/browse/AM-271
Refactor: Refactored the Integration test GetRolePermissionsIntegrationTest  whenGettingRolePermissionsShouldReturnPermissionsAndSecurityClassificationsForSpecifiedRole

Am 271 refactor security classifications for resource attribute

---

am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetResourceDefinitionsWithCreatePermissionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetRolePermissionsIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GrantAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/RevokeAccessIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/base/IntegrationBaseTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/base/PreconfiguredIntegrationBaseTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/RoleIntegrationTest.java
am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/DefaultRoleSetupDataFactory.java
am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/TestConstants.java
am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/TestDataFactory.java

https://tools.hmcts.net/jira/browse/AM-245
Confusing overloaded methods refactored to make code base more readable. 
Randomised Role Name and Other Role Name.

refactor: randomised test data and truncate db before all tests

---

src/gatling/resources/filterResource.json
src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/scenarios/BasicScenarios.scala
src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/simulations/PipelineSimulation.scala
src/main/java/uk/gov/hmcts/reform/amapi/Application.java

https://tools.hmcts.net/jira/browse/AM-303
Fix for Gatling Test failure for Filter-Resource rest API

fix: Gatling test case fix for Filter-Resource (AM-303)

---

am-lib/src/benchmark/java/uk/gov/hmcts/reform/amlib/AccessManagementServiceBenchmarkTest.java
am-lib/src/benchmark/java/uk/gov/hmcts/reform/amlib/AccessManagementServiceBenchmarks.java

Change to update the benchmark tests configuration. Changes included are  -
1. increase the number of iterations
2.  change the  benchmark test mode to ALL from throughput

chore: update benchmark tests configuration

---

am-lib/src/benchmark/java/uk/gov/hmcts/reform/amlib/AccessManagementServiceBenchmarkTest.java
am-lib/src/benchmark/java/uk/gov/hmcts/reform/amlib/AccessManagementServiceBenchmarks.java

NA
- to update the  benchmark test configuration to run only throughput and average time mode
-  to assert only the benchmark test score in Throughput mode

chore:update benchmark tests configuration

---

am-lib/src/main/java/uk/gov/hmcts/reform/amlib/AccessManagementService.java

https://tools.hmcts.net/jira/browse/AM-300
fix: Aspect logging for user highest security classification in Filter resource api

fix: Aspect logging for user highest security classification in Filter resource api

---

.gitignore
migration/ccd-to-am-migration-init.sql
migration/ccd-to-am-migration-main.sql
migration/ccd-to-am-migration-runner.sh

https://tools.hmcts.net/jira/browse/AM-308
Error handling, gap analysis and post ingestion validation for migration.

feat: error handling for db migration scripts (AM-308)

---

am-lib/src/main/java/uk/gov/hmcts/reform/amlib/AccessManagementService.java
am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/AccessManagementRepository.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java

https://tools.hmcts.net/jira/browse/AM-328
check both ResourceId and ResourceType for explicit access records in filterResource() method

feat: AM-328-filterResource add resourceType inaddition to resourceId

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/AM-309
fix:Gatling Testing: Default data insertion(AM-309)

fix:Gatling Testing: Default data insertion(AM-309)

---

Jenkinsfile_nightly
build.gradle
src/gatling/load-or-delete-data.sh

https://tools.hmcts.net/jira/browse/AM-362
fix: gatling fix initial data load Jenkins aat(Am-362)

fix: gatling fix initial data load Jenkins aat(Am-362)

---

Jenkinsfile_nightly
build.gradle
config/owasp/suppressions.xml
src/gatling/load-or-delete-data.sh

https://tools.hmcts.net/jira/browse/AM-362
fix: Vulnerability Tomcat (Am 362 initial test data load)

fix: Vulnerability Tomcat (Am 362 initial test data load)

---

Jenkinsfile_nightly
build.gradle
config/owasp/suppressions.xml
src/gatling/load-or-delete-data.sh

https://tools.hmcts.net/jira/browse/AM-362
fix:Gating test Initial data load Jenkins(AM-362)

Fix:Gating test Initial data load Jenkins(AM-362)

---

build.gradle
src/functionalTest/resources/application-functional.yaml

NA
refactor: enabled smoke test commented in previous commit

refactor: enabled smoke test 

---

am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/AccessManagementRepository.java
am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java

https://tools.hmcts.net/jira/browse/AM-375

fix: filter resource method no longer returns role that doesn't exist (AM-375)

---

Jenkinsfile_nightly
security.sh

https://tools.hmcts.net/jira/browse/AM-387

feat: OWASP ZAP security scan

---

src/functionalTest/java/uk/gov/hmcts/reform/amapi/functional/AccessManangementApiTest.java
src/functionalTest/java/uk/gov/hmcts/reform/amapi/functional/FunctionalTestSuite.java
src/functionalTest/resources/application-functional.yaml
src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/http/AccessManagement.scala
src/integrationTest/java/uk/gov/hmcts/reform/amapi/controllers/AccessManagementControllerTest.java
src/integrationTest/java/uk/gov/hmcts/reform/amapi/exception/AccessManagementResponseEntityExceptionHandlerTest.java
src/main/java/uk/gov/hmcts/reform/amapi/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/amapi/controllers/AccessManagementController.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/amapi/controllers/AccessManagementControllerUnitTest.java
tools/postman-collections/am-lib-testing.postman_collection.json

https://tools.hmcts.net/jira/browse/AM-381
feat: Versioning Api changes AM-381

feat: Versioning Api changes AM-381

---

am-lib/src/benchmark/resources/database-scripts/populate/access_management.copy.sql
am-lib/src/benchmark/resources/database-scripts/populate/access_management.sql

https://tools.hmcts.net/jira/browse/AM-332
refactor: Bench Mark tests fix for new auditing columns

refactor: Bench Mark tests fix for new auditing columns

---

Jenkinsfile_CNP
charts/am-accessmgmt-api/Chart.yaml
charts/am-accessmgmt-api/values.aat.template.yaml
charts/am-accessmgmt-api/values.preview.template.yaml
charts/am-accessmgmt-api/values.yaml

aks migration - changes to jenkins cnp and helm charts

feat:aks migration- changes to jenkins cnp and helm charts

---

am-lib/src/main/resources/db/migration/V21__Audit_Scripts_AM.sql
am-lib/src/main/resources/db/migration/V22__Alter_Audit_Action_Constraint.sql

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/AM-418
Change description
fix: flyway failure fix for audit table

fix: flyway failure fix for audit table

---

am-lib/build.gradle
charts/am-accessmgmt-api/Chart.yaml
charts/am-accessmgmt-api/values.yaml

NA
fix: nightly fix ingressHost

fix: nightly fix ingressHost

---

src/main/java/uk/gov/hmcts/reform/amapi/config/AuthCheckerConfiguration.java

NA
fix: Spring security firewall fix

fix: Spring security firewall fix
